name: CI for Flutter

on: 
  push:
      #branches: 
      #- master
    tags:
      - v1.*
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with: 
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: |
        cd sample_app
        echo "building app for release."
        echo  ${{secrets.KEY_MARKET_PLACE}}
        echo  ${{secrets.ALIAS_PASSWORD}}
        echo  ${{secrets.KEY_PASSWORD}}
        echo $KEY_JKS
        echo $KEY_JKS > android/sample.keystore
        flutter pub get
        flutter build appbundle --target-platform android-arm,android-arm64,android-x64
      env:
        KEY_JKS: ${{secrets.KEY_MARKET_PLACE}}
        KEY_PASSWORD: ${{secrets.ALIAS_PASSWORD}}
        ALIAS_PASSWORD: ${{secrets.KEY_PASSWORD}}
    - name: Push APK to Releases
      uses: ncipollo/release-action@v1
      with:
        artifacts: "sample_app/build/app/outputs/bundle/release/app-release.aab"
        token: ${{ secrets.TOKEN }}
    
      
